# Form implementation generated from reading ui file 'ui/autogenerated/www_game_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WWWGameWindow(object):
    def setupUi(self, WWWGameWindow):
        WWWGameWindow.setObjectName("WWWGameWindow")
        WWWGameWindow.resize(800, 749)
        self.www_game_window_central_widget = QtWidgets.QWidget(parent=WWWGameWindow)
        self.www_game_window_central_widget.setObjectName("www_game_window_central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.www_game_window_central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.www_window_round_info_widget = QtWidgets.QWidget(parent=self.www_game_window_central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.www_window_round_info_widget.sizePolicy().hasHeightForWidth())
        self.www_window_round_info_widget.setSizePolicy(sizePolicy)
        self.www_window_round_info_widget.setObjectName("www_window_round_info_widget")
        self.www_window_round_info_widget_horizontal_layout = QtWidgets.QHBoxLayout(self.www_window_round_info_widget)
        self.www_window_round_info_widget_horizontal_layout.setContentsMargins(20, 10, 20, 10)
        self.www_window_round_info_widget_horizontal_layout.setSpacing(10)
        self.www_window_round_info_widget_horizontal_layout.setObjectName("www_window_round_info_widget_horizontal_layout")
        self.verticalLayout.addWidget(self.www_window_round_info_widget)
        self.www_window_game_widget = QtWidgets.QWidget(parent=self.www_game_window_central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(85)
        sizePolicy.setHeightForWidth(self.www_window_game_widget.sizePolicy().hasHeightForWidth())
        self.www_window_game_widget.setSizePolicy(sizePolicy)
        self.www_window_game_widget.setObjectName("www_window_game_widget")
        self.www_window_game_widget_horizontal_layout = QtWidgets.QHBoxLayout(self.www_window_game_widget)
        self.www_window_game_widget_horizontal_layout.setContentsMargins(20, 20, 20, 20)
        self.www_window_game_widget_horizontal_layout.setObjectName("www_window_game_widget_horizontal_layout")
        self.verticalLayout.addWidget(self.www_window_game_widget)
        WWWGameWindow.setCentralWidget(self.www_game_window_central_widget)

        self.retranslateUi(WWWGameWindow)
        QtCore.QMetaObject.connectSlotsByName(WWWGameWindow)

    def retranslateUi(self, WWWGameWindow):
        _translate = QtCore.QCoreApplication.translate
        WWWGameWindow.setWindowTitle(_translate("WWWGameWindow", "Brain Ring Game"))
