from __future__ import annotations

from typing import TYPE_CHECKING

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QMainWindow

from config.enums import ColorSchemaEnum
from core.mixins import WidgetBuilderMixin
from ui.autogenerated.erudite_game_window_autogenerated import Ui_EruditeGameWindow


if TYPE_CHECKING:
    from PyQt6.QtWidgets import QHBoxLayout

    from core.widgets import ScalableColoredSvgWidget, ScalableLabel


class EruditeGameWindow(QMainWindow, Ui_EruditeGameWindow, WidgetBuilderMixin):
    """Класс, описывающий структуру информационного окна игры "Эрудитка"."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.erudite_game_window_central_widget.setStyleSheet(
            f'background-color: {ColorSchemaEnum.ERUDITE_GAME_WIDGET_BACKGROUND};',
        )
        # наибольший индекс виджета, отображаемого на панели заблокированных игроков
        self.max_displayed_blocked_player_indicator_idx: int = 0

        self.PLAYER_INFO_HORIZONTAL_LAYOUTS: list[QHBoxLayout] = [
            self.erudite_game_player_info_widget_01_horizontal_layout,
            self.erudite_game_player_info_widget_02_horizontal_layout,
            self.erudite_game_player_info_widget_03_horizontal_layout,
            self.erudite_game_player_info_widget_04_horizontal_layout,
            self.erudite_game_player_info_widget_05_horizontal_layout,
            self.erudite_game_player_info_widget_06_horizontal_layout,
        ]

    def populate_player_info_horizontal_layout(
        self,
        layout: QHBoxLayout,
        left_widget: ScalableColoredSvgWidget,
        central_widget: ScalableLabel,
        right_widget: ScalableLabel,
    ):
        """Заполняет виджетами указанный горизонтальный layout на панели информации об игроках."""
        layout.insertWidget(0, left_widget, alignment=Qt.AlignmentFlag.AlignCenter)
        layout.insertWidget(1, central_widget)
        layout.insertWidget(2, right_widget)

    def clear_all_player_info_horizontal_layouts(self) -> None:
        """Удаляет все виджеты с панели информации об игроках."""
        for layout in self.PLAYER_INFO_HORIZONTAL_LAYOUTS:
            while layout.count():
                layout_item = layout.takeAt(0)
                if widget := layout_item.widget():
                    widget.deleteLater()

    def add_widget_to_blocked_players_indicator_layout(self, widget: ScalableColoredSvgWidget):
        """Добавляет виджет на layout, отображающий заблокированных игроков."""
        self.erudite_game_window_blocked_players_indicator_widget_horizontal_layout.insertWidget(
            self.max_displayed_blocked_player_indicator_idx, widget, alignment=Qt.AlignmentFlag.AlignCenter,
        )
        self.max_displayed_blocked_player_indicator_idx += 1

    def clear_blocked_players_indicator_layout(self):
        """Удаляет все виджеты с layout-а, отображающего заблокированных игроков."""
        while self.erudite_game_window_blocked_players_indicator_widget_horizontal_layout.count():
            layout_item = self.erudite_game_window_blocked_players_indicator_widget_horizontal_layout.takeAt(0)
            if widget := layout_item.widget():
                widget.deleteLater()
        self.max_displayed_blocked_player_indicator_idx = 0

    @property
    def first_unpopulated_player_info_layout(self) -> QHBoxLayout:
        """Возвращает первый сверху layout, на котором отсутствуют виджеты."""
        for layout in self.PLAYER_INFO_HORIZONTAL_LAYOUTS:
            if not layout.count():
                return layout
        raise LookupError('Found no unpopulated player info layouts')
