from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QMainWindow

from config.enums import ColorSchemaEnum
from core.mixins import WidgetBuilderMixin
from ui.autogenerated.www_game_window_autogenerated import Ui_WWWGameWindow


class WWWGameWindow(QMainWindow, Ui_WWWGameWindow, WidgetBuilderMixin):
    """Класс, описывающий структуру информационного окна игры "Что-где-когда"."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.www_game_window_central_widget.setStyleSheet(
            f'background-color: {ColorSchemaEnum.WWW_GAME_WIDGET_BACKGROUND};',
        )
        self.www_game_window_round_info_widget = self.build_label_widget(
            text='',
            color=ColorSchemaEnum.WWW_ROUND_STATUS_LABEL,
            bold=True,
        )
        self.www_window_round_info_widget_horizontal_layout.addWidget(self.www_game_window_round_info_widget)

    def update_round_info_widget(
        self,
        text: str = '',
        color: ColorSchemaEnum = ColorSchemaEnum.WWW_ROUND_STATUS_LABEL,
    ) -> None:
        """Обновляет текст и цвет виджета с информацией о статусе раунда на игровом окне (ЧГК)."""
        self.www_game_window_round_info_widget.setText(text)
        new_style = f'color: {color};'
        if self.www_game_window_round_info_widget.font().weight() == QFont.Weight.Bold:
            new_style += ' font-weight: bold;'
        self.www_game_window_round_info_widget.setStyleSheet(new_style)
